<?xml version="1.0" encoding="utf-8"?><Database Name="COMP123" Class="CategoryDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=(localdb)\ProjectsV12;Initial Catalog=COMP123;Integrated Security=True" SettingsObjectName="COMP123_S2016_Ckawakam_300821245_A7.Properties.Settings" SettingsPropertyName="COMP123ConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.Categories" Member="Categories">
    <Type Name="Category">
      <Column Name="CategoryID" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="DownloadCost" Type="System.Double" DbType="Float NOT NULL" CanBeNull="false" />
      <Column Name="Category" Member="Category1" Type="System.String" DbType="NVarChar(30) NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
</Database>